<a href="https://colab.research.google.com/github/silvanaDaza/INTELIGENCIA-ARTIFICIAL---ULEAM/blob/main/LUNES_29_10_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY LIBRARY

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.26.4


In [ ]:
myArray=np.array([1,2,3,4,5])
print(myArray)

[1 2 3 4 5]


In [ ]:
print(type(myArray))

<class 'numpy.ndarray'>


In [ ]:
print(myArray.shape)
print(myArray[2])
myArray[2]=10
print(myArray)

(5,)
3
[ 1  2 10  4  5]


In [ ]:
myArray1=np.array([[1,2,3],[4,5,6]])
print(myArray1)
print(myArray1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
myArray2=np.zeros((5,5))
print(myArray2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
myArray3=np.full((3,6),10)
print(myArray3)
myArray4=np.eye(5)
print(myArray4)
myArray5=np.ones((4,4))
print(myArray5)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
myArray6=np.random.random((5,5))
print(myArray6)

[[0.58765103 0.58345762 0.20540875 0.22181229 0.88475733]
 [0.73155779 0.33345623 0.77238027 0.82081574 0.43915797]
 [0.38390072 0.94068751 0.8065656  0.23135949 0.16234933]
 [0.6722954  0.16507429 0.7330845  0.94346015 0.46124828]
 [0.24908624 0.34738094 0.61831905 0.46033626 0.63149258]]


In [ ]:
myArray7=np.random.randint(100,size=(5,5))
print(myArray7)

[[78 79 51 96 68]
 [46 47 72 78 23]
 [47  9 98 74 31]
 [ 3 19 75 70 27]
 [67 51 90 23 37]]


In [ ]:
newMatrix=myArray7[:2,:2]
print(newMatrix)

[[78 79]
 [46 47]]


In [ ]:
myArray7[2,2]=100
print(myArray7)

[[ 78  79  51  96  68]
 [ 46  47  72  78  23]
 [ 47   9 100  74  31]
 [  3  19  75  70  27]
 [ 67  51  90  23  37]]


In [ ]:
print(myArray7[2,:])

[ 47   9 100  74  31]


In [ ]:
print(myArray7[:,2])

[ 51  72 100  75  90]


In [ ]:
print(myArray7[:,2].shape)

(5,)


In [ ]:
subMatrix=myArray7[1:4,1:4]
print(subMatrix)

[[ 47  72  78]
 [  9 100  74]
 [ 19  75  70]]
