<a href="https://colab.research.google.com/github/silvanaDaza/INTELIGENCIA-ARTIFICIAL---ULEAM/blob/main/Martes_5_11_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#
import numpy as np
martrixA=np.array([[11, 12, 13, 14], [21, 22, 23, 24],[31, 32, 33, 34]])
print(martrixA.shape)

(3, 4)


In [3]:
martrixA

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [4]:
print(martrixA[1:, 1:3])

[[22 23]
 [32 33]]


In [5]:
matrixB=np.random.randint(0,10, size=(4,3))
print(matrixB)
print(matrixB.shape)

[[7 8 2]
 [7 9 4]
 [6 3 1]
 [4 1 8]]
(4, 3)


In [9]:
print(matrixB)
#

[[7 8 2]
 [7 9 4]
 [6 3 1]
 [4 1 8]]


In [7]:
print(matrixB)
col_indices=np.array([0,1,2])
row_indices=np.array([1,2])

for row, col in zip(row_indices, col_indices):
    #print(row, ",", col)
    print(matrixB[row, col])

[[7 8 2]
 [7 9 4]
 [6 3 1]
 [4 1 8]]
7
3


In [10]:
mask=matrixB>7
print(mask)

[[False  True False]
 [False  True False]
 [False False False]
 [False False  True]]


In [11]:
print(matrixB[mask])


[8 9 8]


In [12]:
print(matrixB[matrixB>7])

[8 9 8]


In [13]:
print(matrixB)

[[7 8 2]
 [7 9 4]
 [6 3 1]
 [4 1 8]]


In [14]:
matrixB[matrixB%2==0]+=100
print(matrixB)

[[  7 108 102]
 [  7   9 104]
 [106   3   1]
 [104   1 108]]


In [15]:
print(matrixB)

[[  7 108 102]
 [  7   9 104]
 [106   3   1]
 [104   1 108]]


In [18]:
matrixC =np.random.rand(2,2)

In [19]:
filter =(matrixB>3) & (matrixB<8)
matrixB[filter]+=100
print(matrixB)

[[107 208 202]
 [107 109 204]
 [106   3   1]
 [104   1 108]]


In [20]:
matrixA1 = np.random.randint(0,10, size=(2,2))
matrixA2 = np.random.randint(0,10, size=(2,2))
print("Matrix A1")
print(matrixA1)
print("Matrix A2")
print(matrixA2)

Matrix A1
[[2 3]
 [3 5]]
Matrix A2
[[9 1]
 [3 2]]


In [21]:
print(matrixA1+matrixA2)
print(matrixA1-matrixA2)
print(matrixA1*matrixA2)
print(matrixA1/matrixA2)
print(np.sqrt(matrixA1))

[[11  4]
 [ 6  7]]
[[-7  2]
 [ 0  3]]
[[18  3]
 [ 9 10]]
[[0.22222222 3.        ]
 [1.         2.5       ]]


In [22]:
print(matrixA1)


[[2 3]
 [3 5]]


In [23]:
print(np.sqrt(matrixA1))

[[1.41421356 1.73205081]
 [1.73205081 2.23606798]]


In [24]:
matrixA1 =np.random.randint(0,10, size=(2,2))
print(matrixA1)

[[1 1]
 [6 3]]


In [25]:
print(np.mean(matrixA1))

2.75


In [27]:
print(matrixA1.mean(axis=1))

[1.  4.5]


In [28]:
print(matrixA1.mean(axis=0))

[3.5 2. ]


In [29]:
print(np.std(matrixA1))

2.0463381929681126


In [30]:
print(np.median(matrixA1))

2.0


In [32]:
print(matrixA1.max())

6
6


In [33]:
print(matrixA1.sum())

11


In [34]:
start=np.zeros((4,2))
print(start)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [35]:
add_rows=np.array([1,2,3])
print(add_rows.shape)

(3,)


In [59]:
print(start)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [43]:
col_rows=np.array([[1,2,3,4]])

In [44]:
print(start)
tmp=col_rows.T
y2=start+tmp
print(y2)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [2. 2.]
 [3. 3.]
 [4. 4.]]


In [57]:
tmp1=np.array([[1,1],[2,2]])
tmp2=np.array([[3,3],[4,4]])
print(tmp1)
print(tmp2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [58]:
print(np.dot(tmp1,tmp2))

[[ 7  7]
 [14 14]]


In [52]:
y1=np.random.randint(low=2, high=10, size=(2,2))
y2=np.random.randint(low=2, high=10, size=(2,2))
print(y1)
print(y2)

[[6 2]
 [7 3]]
[[5 3]
 [9 3]]


In [53]:
np.vstack((y1,y2))

array([[6, 2],
       [7, 3],
       [5, 3],
       [9, 3]])

In [54]:
np.hstack((y1,y2))

array([[6, 2, 5, 3],
       [7, 3, 9, 3]])